name: Test Workflow

on: push

jobs:
  test:
    name: Attempt to use Ruby and Mono in the same context
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
      - run: sudo apt list --installed
      - run: sudo apt-get install nuget
      - run: ruby --version
      - run: bundle --version
      - run: mono --version
      - run: which nuget
      - run: which msbuild
