name: Test Workflow

on: push

jobs:
  test:
    name: Attempt to use Ruby and Mono in the same context
    runs-on: ubuntu-16.04
    container:
      image: mono:6.8.0

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
      - run: ruby --version
      - run: which bundle
      - run: ls -l $(which bundle)
      - run: sh -c 'bundle --version 2>&1'
      - run: find ${HOME}
      - uses: docker://debian:latest
        with:
          entrypoint: touch
          args: /github/home/testfile
      - run: find ${HOME}
      - run: which ruby
      - run: which bundle
      - run: bundle --version
