name: Test Workflow

on: push

jobs:
  test:
    name: Attempt to use Ruby and Mono in the same context
    runs-on: ubuntu-18.04
    container:
      image: josephwong/ubuntu-mono:0.1_mono-6.8.0.105_bionic

    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt-get install sudo
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
      - run: ruby --version
      - run: bundle --version
      - run: mono --version
      - run: which nuget
